### ISSUE TITLE
Subscription stops updating when MongoDB gets busy.

### ISSUE THREAD

**Issue by landland** [radekmie/changestream-to-redis#2]
I have been using redis-oplog, disable-oplog, and changestream-to-redis for about a month across multiple large apps sharing a common MongoDB. We needed it as we were running into performance issues with just MongoDB (CPU hosed at 100%, apps very slow).

It works great and has significantly reduced our MongoDB load. However, when MongoDB does get busy, maybe a sustained 80-90% CPU usage for an hour or more, updates just stop on the apps. 

For example, we have a MongoDB collection with a single document in it and when things get busy we switch a boolean flag in the document so that apps that are subscribed to this collection through a Meteor publication get notified. However, it never comes through. Only after we restart the apps does the client-side subscription get the update.

Any ideas on what might be causing this? I'm not sure if it is a redis-oplog issue or changestream-to-redis thing or unrelated, but this behaviour doesn't happen with oplog enabled (the subscription comes through but everything else slows to a crawl). Thanks for any insights you might be able to provide.

**Comment by radekmie** [comment]
Hi @landland, thanks for reaching out!

We had a couple of "high CPU periods", but I have never seen it impact the reactivity in any way. When this happens, is it only this one collection, or is all of the reactivity gone?

You said that restarting an app helped; did you try to restart the `changestream-to-redis` instead? Maybe it restarts on its own?

My first idea would be that you're running out of storage for oplog (Change Streams take more storage than oplog alone thanks to pre- and post-images), which leads to a situation where the Change Stream fails (`changestream-to-redis` cannot process it further, because the resume token is already out). When this happens, it restarts, picking up the latest change, skipping everything in between.

**EDIT:** Can you check your "Replication Oplog Window" metric of your MongoDB instance? Does it go to zero at any time?

**Comment by landland** [comment]
Hi @radekmie, thanks for your response.

From what I can tell, on one application all reactivity is gone, not just on the single document collection. On a separate application, it looks like existing document updates continue usually, but newly inserted documents do not get displayed. Refreshing the pages does not help, only restarting the applications does.

We did try restarting changestream-to-redis as well, but that did not help, either.

I had to look up what the "Replication Oplog Window" metric was. We use Digital Ocean's managed MongoDB and it does not include replication metrics. If you have a recommendation on a good monitoring tool that will include this info I'm happy to give it a try so we can get to the bottom of this. Alternatively, if there are any mongo commands you'd like me to run the next time this happens please let me know, as well. Thanks!

**Comment by radekmie** [comment]
> We did try restarting changestream-to-redis as well, but that did not help, either.

But did you check whether it restarts on its own maybe? I suspect it may.

> I had to look up what the "Replication Oplog Window" metric was. We use Digital Ocean's managed MongoDB and it does not include replication metrics. [...]

I'm just so used to Atlas 😅 You can run [`db.getReplicationInfo().timeDiff`](https://www.mongodb.com/docs/manual/reference/method/db.getReplicationInfo/#mongodb-data-db.getReplicationInfo--.timeDiff) and see. If it matches the time spent since the last incident, that's most likely the issue: not enough size for oplog.

**Comment by landland** [comment]
> But did you check whether it restarts on its own maybe? I suspect it may.

I am not sure I follow. Do you mean leave everything alone long enough for the apps to eventually start receiving the updates? We did do that the first time, and yes it did recover but it was a few hours later from when the issue started.

If that's not what you mean, please clarify so I can give a better answer :)

> You can run [db.getReplicationInfo().timeDiff](https://www.mongodb.com/docs/manual/reference/method/db.getReplicationInfo/#mongodb-data-db.getReplicationInfo--.timeDiff) and see. If it matches the time spent since the last incident, that's most likely the issue: not enough size for oplog.

Ok thanks, I'll run this timeDiff command at various intervals the next time reactivity stops to see if the time is the same. If this is indeed the issue with not enough size for oplog, is there a fix/workaround?

**Comment by radekmie** [comment]
> I am not sure I follow. Do you mean leave everything alone long enough for the apps to eventually start receiving the updates? [...]

No, and sorry for not making myself clear earlier 🙈 I thought about whether the `changestream-to-redis` restarted itself, i.e., whether the binary/Docker image quit and started again (due to auto restarting policy, etc.). You can check the logs to see if it happened or not.

If it did, that's a clear indication the Change Stream failed (most likely due to not enough space for oplog).

> [...] If this is indeed the issue with not enough size for oplog, is there a fix/workaround?

You can always [give it more space](https://www.mongodb.com/docs/manual/tutorial/change-oplog-size/).

**Comment by landland** [comment]
> No, and sorry for not making myself clear earlier 🙈 I thought about whether the changestream-to-redis restarted itself, i.e., whether the binary/Docker image quit and started again (due to auto restarting policy, etc.). You can check the logs to see if it happened or not.

Ah, understood. No need to apologize, you're doing amazing work. In this case, at one time changestream-to-redis did stop once when we were first testing it out. Then we added a docker restart policy. During the incidents when reactivity stops on the apps, changestream-to-redis is still running when we checked the docker logs. 

The docker container was stopped and started 6 days ago and an incident hasn't yet happened. When it does we'll be sure to check the events log to see if a restart occurs.

> You can always [give it more space](https://www.mongodb.com/docs/manual/tutorial/change-oplog-size/).

Thank you, will check this out!

**Comment by radekmie** [comment]
Did you have a chance to check it maybe, @landland?

**Comment by landland** [comment]
Nothing yet. We've made various optimizations so haven't encountered the problem lately. When it does happen again I'll be sure to provide an update.

**Comment by radekmie** [comment]
Sure, no problem. I'll close this issue in the meantime, but please do let me know here!

**Comment by landland** [comment]
Hi @radekmie just an update that it still happens from time to time where the updates/reactivity are very slow. I ran the timeDiff command as you suggested and here is some sample output from today.

87501
87502
87503
87504

Based on this sample, do you still recommend increasing the oplog size? If so, do you know what a best practice is to increase the oplog size to (for example, is there too big of a size)?

**Comment by radekmie** [comment]
87501 seconds is over a day, so there's plenty of space for the messages... I think the only thing we could do here would be to expose some metrics (including a timestamp of the last processed change event), and check it the next time it happens. I'll create an issue for that but cannot guarantee when I'll have time to work on it.
